### ISSUE TITLE
Cannot import efficiency-nodes-comfyui module when launch ComfyUI NameError: name 'latent_versions_updated' is not defined

### ISSUE THREAD

**Issue by whmc76** [LucianoCirino/efficiency-nodes-comfyui#123]
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1698, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\__init__.py", line 1, in <module>
    from .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 3945, in <module>
    class TSC_HighRes_Fix:
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 3955, in TSC_HighRes_Fix
    upscale_methods = default_upscale_methods + latent_versions_updated
NameError: name 'latent_versions_updated' is not defined

Cannot import E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui module for custom nodes: name 'latent_versions_updated' is not defined

**Comment by whmc76** [comment]
today after update the node, it failed import
