### ISSUE TITLE
[Bug] Import failed with a venv in the python_embedded folder

### ISSUE THREAD

**Issue by mizukarada** [LucianoCirino/efficiency-nodes-comfyui#154]
My venv is in the same folder as the `python_embedded` folder at `C:\Users\Anon\Downloads\Programs\ComfyUI_windows_portable\python_embeded`. This makes `python_embeded\python.exe` lose pip functionality but in turn I get to use the venv python.exe at  `python_embeded\Scripts\python.exe`. I did this to share venvs with ComfyUI and stable-diffusion-webui, but efficiency nodes throw an error.

Stack trace:
```shell
C:\Users\Anon\Downloads\Programs\ComfyUI_windows_portable\python_embeded\python.exe: No module named pip
Traceback (most recent call last):
  File "C:\Users\Anon\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1725, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Anon\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\__init__.py", line 1, in <module>
    from .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "C:\Users\Anon\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 41, in <module>
    from tsc_utils import *
  File "C:\Users\Anon\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_utils.py", line 521, in <module>
    install_packages(my_dir)
  File "C:\Users\Anon\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_utils.py", line 492, in install_packages
    installed_packages = packages(embedded_python_exe if use_embedded else None, versions=False)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anon\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_utils.py", line 516, in packages
    subprocess.check_output([python_exe, '-m', 'pip', 'freeze']).split()]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "subprocess.py", line 466, in check_output
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['C:\\Users\\Anon\\Downloads\\Programs\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'freeze']' returned non-zero exit status 1.

Cannot import C:\Users\Anon\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui module for custom nodes: Command '['C:\\Users\\Anon\\Downloads\\Programs\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'freeze']' returned non-zero exit status 1.
```

**Comment by LucianoCirino** [comment]
I am aware of this issue and will attempt to have a fix this weekend.

**Comment by LucianoCirino** [comment]
I made a branch to test, hopefully it handle these errros more gracefully. Please test -> https://github.com/LucianoCirino/efficiency-nodes-comfyui/tree/Update-Failure-to-Install-Dependencies

The new changes will let you run the nodes but it will throw errors that it failed to install requirements.
You will have to manually install the requirements yourself.

```
pip install simpleeval websockets
```

**Comment by mizukarada** [comment]
While that commit prevents the extension from crashing (I get get module pip not found error now), why not use `sys.executable` like `subprocess.check_call([sys.executable, "-m", "pip", "install", module_name])`?

**Comment by LucianoCirino** [comment]
Please test again using this branch:
https://github.com/LucianoCirino/efficiency-nodes-comfyui/tree/Use-sys.executable-for-Pip-Calls

commit: https://github.com/LucianoCirino/efficiency-nodes-comfyui/pull/165/commits

**Comment by mizukarada** [comment]
Still getting the message:
```shell
C:\Users\Anon\Downloads\Programs\ComfyUI_windows_portable\python_embeded\python.exe: No module named pip
Efficiency Nodes: An unexpected error occurred during the package installation process. Failed!
Please try manually installing the required packages from the requirements.txt file.
```

But no issues if you change 
https://github.com/LucianoCirino/efficiency-nodes-comfyui/blob/359ff0f7888100119cc31065c16d688d48e34ca9/tsc_utils.py#L487

to 

```python
    use_embedded = os.path.exists(embedded_python_exe) and embedded_python_exe == sys.executable
```

**Comment by LucianoCirino** [comment]
Applied -> https://github.com/LucianoCirino/efficiency-nodes-comfyui/pull/165/commits/1479ea36a4a1e459318b5a42444aefcacc9112f6

And merged ->https://github.com/LucianoCirino/efficiency-nodes-comfyui/pull/165/files

**Comment by mizukarada** [comment]
Thanks!
