### ISSUE TITLE
NameError: name 'model_lora_keys_unet' is not defined

### ISSUE THREAD

**Issue by audioscavenger** [LucianoCirino/efficiency-nodes-comfyui#197]
cannot load any lora in the loader:

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\GPT\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\GPT\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\GPT\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\GPT\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 101, in efficientloader
    model, clip = load_lora(lora_params, ckpt_name, my_unique_id, cache=lora_cache, ckpt_cache=ckpt_cache, cache_overwrite=True)
  File "E:\GPT\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_utils.py", line 319, in load_lora
    lora_model, lora_clip = recursive_load_lora(lora_params, ckpt, clip, id, ckpt_cache, cache_overwrite, folder_paths)
  File "E:\GPT\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_utils.py", line 310, in recursive_load_lora
    lora_model, lora_clip = load_lora_for_models_tsc(ckpt, clip, lora_path, strength_model, strength_clip)
  File "E:\GPT\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_sd.py", line 122, in load_lora_for_models_tsc
    key_map = model_lora_keys_unet(model.model)
NameError: name 'model_lora_keys_unet' is not defined

**Comment by audioscavenger** [comment]
i see the project has not changed in a month... why was it working last month then? could it be because Comfy got updated ?

**Comment by humiao1993** [comment]
I encountered the same problem, have you solved it?
