### ISSUE TITLE
TypeError: VAE.__init__() got an unexpected keyword argument 'ckpt_path'

### ISSUE THREAD

**Issue by mysteriousHerb** [LucianoCirino/efficiency-nodes-comfyui#203]
I have taken a short break of few days, and when i am back onto the comfyui, i have bumped into this bug...?

```
  File "D:\stable-diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\stable-diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\stable-diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\stable-diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 226, in efficientloaderSDXL
    return super().efficientloader(base_ckpt_name, vae_name, clip_skip, lora_name, lora_model_strength, lora_clip_strength,
  File "D:\stable-diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 177, in efficientloader
    vae = load_vae(vae_name, my_unique_id, cache=vae_cache, cache_overwrite=True)
  File "D:\stable-diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_utils.py", line 253, in load_vae
    vae = comfy.sd.VAE(ckpt_path=vae_path)
TypeError: VAE.__init__() got an unexpected keyword argument 'ckpt_path'

Prompt executed in 1.77 seconds
```

**Comment by hackingchen** [comment]
I'm seeing the same error here,too

**Comment by NolenBrolen** [comment]
Having the same issue. Indeed only occurs when any VAE other than BakedVAE is selected.
I'm using the `extra_model_paths.yaml` file to link to my A1111 folder with all my models/loras/VAE. I tried moving my VAE's to the ComfyUI/Models/VAE folder, but error  still occurs. 

StackTrace from Console:
`loading new
Global Step: 274189
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\Users\G4G\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\G4G\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\G4G\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\G4G\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 177, in efficientloader
    vae = load_vae(vae_name, my_unique_id, cache=vae_cache, cache_overwrite=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\G4G\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_utils.py", line 254, in load_vae
    vae = comfy.sd.VAE(sd=sd)
          ^^^^^^^^^^^^^^^^^^^
TypeError: VAE.__init__() got an unexpected keyword argument 'sd'

Prompt executed in 0.77 seconds`

**Comment by LucianoCirino** [comment]
Update comfy & repo

**Comment by Dekita** [comment]
I'm seeing this same error with a freshly dockerized build using the latest versions of all things :(

**Comment by xalildd** [comment]
update  efficiency-nodes-comfyui-main
