### ISSUE TITLE
Comfy hangs during startup after updating to v2.0

### ISSUE THREAD

**Issue by alexopus** [LucianoCirino/efficiency-nodes-comfyui#205]
Comfy hangs during startup after updating to v2.0.
Interrupting the hang with ctrl+c prints following stack trace:

```
Using pytorch cross attention
FizzleDorf Custom Nodes: Loaded
Searge-SDXL v4.2 in /home/user/dev/comfy/custom_nodes/SeargeSDXL
^CTraceback (most recent call last):
  File "/home/user/dev/comfy/main.py", line 164, in <module>
    init_custom_nodes()
  File "/home/user/dev/comfy/nodes.py", line 1805, in init_custom_nodes
    load_custom_nodes()
  File "/home/user/dev/comfy/nodes.py", line 1771, in load_custom_nodes
    success = load_custom_node(module_path, base_node_names)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/comfy/nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/dev/comfy/custom_nodes/efficiency-nodes-comfyui/__init__.py", line 1, in <module>
    from .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "/home/user/dev/comfy/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 45, in <module>
    from tsc_utils import *
  File "/home/user/dev/comfy/custom_nodes/efficiency-nodes-comfyui/tsc_utils.py", line 577, in <module>
    install_packages(my_dir)
  File "/home/user/dev/comfy/custom_nodes/efficiency-nodes-comfyui/tsc_utils.py", line 540, in install_packages
    installed_packages = packages(embedded_python_exe if use_embedded else None, versions=False)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/comfy/custom_nodes/efficiency-nodes-comfyui/tsc_utils.py", line 567, in packages
    subprocess.getoutput([sys.executable, "-m", "pip", "freeze"]).splitlines()]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 691, in getoutput
    return getstatusoutput(cmd, encoding=encoding, errors=errors)[1]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 671, in getstatusoutput
    data = check_output(cmd, shell=True, text=True, stderr=STDOUT,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1196, in communicate
    stdout = self.stdout.read()
             ^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

Tried nuking the efficiency custom nodes directory (which solves the hang) and reinstalling the extension from scratch, but still the same result.

**Comment by LucianoCirino** [comment]
I nuked my auto package installer so this wont happen again. Try again.

**Comment by var1ableX** [comment]
> I nuked my auto package installer so this wont happen again. Try again.

Thanks - this worked for me!

**Comment by alexopus** [comment]
Looks good now, thanks!
