### ISSUE TITLE
HighRes-Fix script

### ISSUE THREAD

**Issue by Sandersm90** [LucianoCirino/efficiency-nodes-comfyui#208]
Hey..

Great set of nodes you've made, really simplifies workflow setup. Thanks!
I was wondering if i missed something, otherwise would like to report a bug.
Been messing with the last update and cant seem to use the HighRes-Fix script anymore as it keeps asking for a pixel_upscaler and a control_net_name..
i have selected Latent as upscale_type so didnt think i would need a pixel upscaler, neither am i using control net in this workflow.

This is the prompt ComfyUI is giving me:
![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/1882926/73f69ab5-0b5e-452d-ad88-02af88d48313)

Do i need a pixel upscaler now and/or did the highres script become control net only?

Any suggestions?

**Comment by LucianoCirino** [comment]
Can you please send me a text-copy of the error you receive on the command line window?

**Comment by Sandersm90** [comment]
Command-line output

```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "F:\ai\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ai\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ai\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TSC_HighRes_Fix.hires_fix_script() missing 2 required positional arguments: 'pixel_upscaler' and 'control_net_name'
```

**Comment by LucianoCirino** [comment]
Dumb question, but did you try loading a new instance of the node?

**Comment by Sandersm90** [comment]
Yes i tried, and the only thing that seems to work for me is when i completely restart Comfy, so it loads all fresh but with its previous saved workflow.

Maybe interesting to know: this started after i put in the AnimateDiff script because of a random misclick, i removed it without using it tho.

**Comment by realcarlos** [comment]
same issues 

![Screenshot from 2023-10-23 21-16-03](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/13853/68ddaf55-68be-481d-a032-08b17480e49f)
![Screenshot from 2023-10-23 21-16-42](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/13853/11fb323c-dec5-4b72-bbd0-f7ae5e381197)

**Comment by lauretta91** [comment]
I've got the same but only pixel upscaler is required :)
![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/87091589/553cbe12-0843-407b-844d-5f6b09ffd627)

**Comment by yunwuhai** [comment]
same to me
![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/49578095/163f5144-5530-47cc-abd6-d6e4f33f0373)

> I've got the same but only pixel upscaler is required :) ![image](https://user-images.githubusercontent.com/87091589/277986121-553cbe12-0843-407b-844d-5f6b09ffd627.png)

**Comment by JohnGitting** [comment]
I don't know the fix for the "pixel_upscaler", but the reason you have "control_net_name" error is because you have no controlnet models installed

**Comment by JarekDerp** [comment]
Ah well, my problem went away after installing T2I-Adapters models and restarting comfyui + browser. Strange that it check if you have any control net models even if you're not doing any controlnet tasks.

**Comment by emily2023ai** [comment]
I had the same problem, and my solution was to install the following node for the control_net_name problem. Install the ComfyUI's ControlNet Auxiliary Preprocessors node, you can search for it in confyui manager or through this link https://github.com/Fannovel16/comfyui_controlnet_aux . I did not have the problem with pixer_upscaler, in that case I recommend installing the ComfyUI_UltimateSDUpscale node, you can find it in confyui manager or directly from this link https://github.com/ssitu/ComfyUI_UltimateSDUpscale try it to see if it works for you.

**Comment by LOKSTED** [comment]
I was able to workaround this by copying the Highres fix node from this example
https://github.com/LucianoCirino/efficiency-nodes-comfyui/blob/v2.0/workflows/HiResFix%20Script.png

**Comment by lampewebdev** [comment]
I needed also to use @LOKSTED work around. I have the same problem as the Original author.

Tested it on 2 machines and both have the same problem
