### ISSUE TITLE
TypeError: VAE.__init__() got an unexpected keyword argument 'sd'

### ISSUE THREAD

**Issue by cardenluo** [LucianoCirino/efficiency-nodes-comfyui#210]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 236, in efficientloaderSDXL
    return super().efficientloader(base_ckpt_name, vae_name, clip_skip, lora_name, lora_model_strength, lora_clip_strength,
  File "F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 183, in efficientloader
    vae = load_vae(vae_name, my_unique_id, cache=vae_cache, cache_overwrite=True)
  File "F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_utils.py", line 299, in load_vae
    vae = comfy.sd.VAE(sd=sd)
TypeError: VAE.__init__() got an unexpected keyword argument 'sd'

**Comment by cardenluo** [comment]
![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/133877069/b720c55c-03b3-4faa-a246-4c0294fabc08)
help to check ,what is wrong with VAE

**Comment by LucianoCirino** [comment]
update ComfyUI

**Comment by cardenluo** [comment]
you are right .
the nodes you have developed are so useful that I have set it to start by default.  thank you ,
