### ISSUE TITLE
Latest ComfyUI Commit looks like it's Stopped using Samplers.Py

### ISSUE THREAD

**Issue by lord-lethris** [LucianoCirino/efficiency-nodes-comfyui#235]
Getting an Error loading **efficiency-nodes-comfyui**

```
ImportError: cannot import name 'CompVisVDenoiser' from 'comfy.samplers' (D:\apps\SD-WebUI\ComfyUI\comfy\samplers.py)

Cannot import D:\apps\SD-WebUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui module for custom nodes: cannot import name 'CompVisVDenoiser' from 'comfy.samplers' (D:\apps\SD-WebUI\ComfyUI\comfy\samplers.py)
```

I "think" (_fishing about for an answer_) that ComfyUI no longer uses K_Sampler - Or at least the location where efficiency-nodes-comfyui looks for it?

![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/1736720/f07d767e-7bf9-4bbb-bffb-3148162c8f0f)

![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/1736720/4db59ff1-8b36-4d19-b24d-e5021fdf6be4)

**Comment by xueqing0622** [comment]
same error:
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\__init__.py", line 1, in <module>
    from .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "F:\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 46, in <module>
    from .py import smZ_cfg_denoiser
  File "F:\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\py\smZ_cfg_denoiser.py", line 7, in <module>
    from comfy.samplers import KSampler, CompVisVDenoiser, KSamplerX0Inpaint
ImportError: cannot import name 'CompVisVDenoiser' from 'comfy.samplers' (F:\ComfyUI\ComfyUI\comfy\samplers.py)

Cannot import F:\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui module for custom nodes: cannot import name 'CompVisVDenoiser' from 'comfy.samplers' (F:\ComfyUI\ComfyUI\comfy\samplers.py)

**Comment by HaydenReeve** [comment]
The author isn't maintaining this repo anymore, so someone will either have to submit a PR or make a fork.

**Comment by lord-lethris** [comment]
It maybe being addressed here ->

https://github.com/jags111/efficiency-nodes-comfyui/issues/10

**Comment by picobyte** [comment]
I posted a fix in the other thread.

**Comment by jags111** [comment]
okay looking into this and will update. Move same to my fork which takes care of the issues as of now.

**Comment by h3clikejava** [comment]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/home/h3c/Documents/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/h3c/Documents/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/h3c/Documents/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/h3c/Documents/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 700, in sample
    samples, images, gifs, preview = process_latent_image(model, seed, steps, cfg, sampler_name, scheduler,
  File "/home/h3c/Documents/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 503, in process_latent_image
    positive_hash = tensor_to_hash(positive[0][0])
  File "/home/h3c/Documents/ComfyUI/custom_nodes/efficiency-nodes-comfyui/tsc_utils.py", line 96, in tensor_to_hash
    byte_repr = tensor.cpu().numpy().tobytes()  # Convert tensor to bytes
AttributeError: 'NoneType' object has no attribute 'cpu'
