### ISSUE TITLE
After updating the latest ComfyUI, an error occurred.

### ISSUE THREAD

**Issue by dream20201212** [LucianoCirino/efficiency-nodes-comfyui#238]
Traceback (most recent call last):
  File "/home/ComfyUI-master/nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ComfyUI-master/custom_nodes/efficiency-nodes-comfyui/__init__.py", line 1, in <module>
    from .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "/home/ComfyUI-master/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 46, in <module>
    from .py import smZ_cfg_denoiser
  File "/home/ComfyUI-master/custom_nodes/efficiency-nodes-comfyui/py/smZ_cfg_denoiser.py", line 7, in <module>
    from comfy.samplers import KSampler, CompVisVDenoiser, KSamplerX0Inpaint
ImportError: cannot import name 'CompVisVDenoiser' from 'comfy.samplers' (/home/ComfyUI-master/comfy/samplers.py)

**Comment by JAssertz** [comment]
This is a result of the comfyUI change made a few days ago removing the "CompVisVDenoiser" you can view the changes in the commit here

[https://github.com/comfyanonymous/ComfyUI/commit/1777b54d0217e77a6a64b0a587b9b11a48e3bf02](https://github.com/comfyanonymous/ComfyUI/commit/1777b54d0217e77a6a64b0a587b9b11a48e3bf02)

**Comment by h3clikejava** [comment]
How to solve it?

**Comment by JAssertz** [comment]
Currently toxicwind has a [fork](https://github.com/toxicwind/efficiency-nodes-comfyui-updates/tree/main) open that should allow it to work the other option is to re-add the missing section of code to the updated file.

**Comment by NeoAnthropocene** [comment]
> Currently toxicwind has a [fork](https://github.com/toxicwind/efficiency-nodes-comfyui-updates/tree/main) open that should allow it to work the other option is to re-add the missing section of code to the updated file.

If it won't be a trouble for you, would you mind to write how we can do that, please?

**Comment by gik0geck0** [comment]
Switching forks in git:
```
cd ComfyUI/custom_nodes/efficiency-nodes-comfyui`
git remote add toxicwind https://github.com/toxicwind/efficiency-nodes-comfyui-updates.git
git fetch toxicwind
git checkout toxicwind/main
```
note: this is a detached head; if you wanted to resolve, `git checkout -b some_interesting_named_branch` -- I just leave it, since this is just temporary

Later, presumably when "this" efficiency-nodes does an update:
```
git fetch origin
git checkout main
git pull
git remote remove toxicwind
```
For more info: https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes and https://stackoverflow.com/questions/10228760/how-do-i-fix-a-git-detached-head

**Comment by gik0geck0** [comment]
That fork gives me the following error, which has been fixed in main-line. Use at your own risk; still hoping this issue gets some attention.
https://github.com/LucianoCirino/efficiency-nodes-comfyui/commit/5db11dc843200198347264ca00d78b6bbb88de60#commitcomment-131987497

**Comment by gik0geck0** [comment]
This commit brings the removed code back over. Works for me, and prods' branch also fixes the above issue as well.
https://github.com/prods/efficiency-nodes-comfyui/commit/05792e360a8b803241659b6f56318cfabad3263b

**Comment by andreszs** [comment]
> This commit brings the removed code back over. Works for me, and prods' branch also fixes the above issue as well. [prods@05792e3](https://github.com/prods/efficiency-nodes-comfyui/commit/05792e360a8b803241659b6f56318cfabad3263b)

I can confirm that repo fixes the _CompVisVDenoiser_ error from original extension.

However I had to fix all my efficient node values because with this version, all values were displaced from their original input boxes.
