### ISSUE TITLE
Efficiency Nodes Warning: Failed to import python package 'simpleeval'; related nodes disabled.

### ISSUE THREAD

**Issue by DezorianGuv** [LucianoCirino/efficiency-nodes-comfyui#239]
Does this error ring a bell to someone? I just copied the folders "simpleeval-0.9.13.tar" and "simpleeval-0.9.13" into the custom_nodes folder in order to get the "efficiency nodes comfyui" to work. How do I get this to work? 

Traceback (most recent call last):
  File "C:\Users\fires\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\fires\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\simpleeval-0.9.13.tar\\__init__.py'

Cannot import C:\Users\fires\ComfyUI_windows_portable\ComfyUI\custom_nodes\simpleeval-0.9.13.tar module for custom nodes: [Errno 2] No such file or directory: 'C:\\Users\\fires\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\simpleeval-0.9.13.tar\\__init__.py'

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): C:\Users\fires\ComfyUI_windows_portable\ComfyUI\custom_nodes\simpleeval-0.9.13.tar
   0.0 seconds: C:\Users\fires\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: C:\Users\fires\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.4 seconds: C:\Users\fires\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

**Comment by wangwenqiao666** [comment]
pip install simpleeval
