### ISSUE TITLE
cannot import name 'CompVisVDenoiser' from 'comfy.samplers'

### ISSUE THREAD

**Issue by momognu** [LucianoCirino/efficiency-nodes-comfyui#247]
ImportError: cannot import name 'CompVisVDenoiser' from 'comfy.samplers'

**Comment by suito-venus** [comment]
```
Traceback (most recent call last):
  File "C:\workspaces_c\comfyUI_20231115\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\workspaces_c\comfyUI_20231115\ComfyUI\custom_nodes\efficiency-nodes-comfyui\__init__.py", line 1, in <module>
    from .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "C:\workspaces_c\comfyUI_20231115\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 46, in <module>
    from .py import smZ_cfg_denoiser
  File "C:\workspaces_c\comfyUI_20231115\ComfyUI\custom_nodes\efficiency-nodes-comfyui\py\smZ_cfg_denoiser.py", line 7, in <module>
    from comfy.samplers import KSampler, CompVisVDenoiser, KSamplerX0Inpaint
ImportError: cannot import name 'CompVisVDenoiser' from 'comfy.samplers' (C:\workspaces_c\comfyUI_20231115\ComfyUI\comfy\samplers.py)

Cannot import C:\workspaces_c\comfyUI_20231115\ComfyUI\custom_nodes\efficiency-nodes-comfyui module for custom nodes: cannot import name 'CompVisVDenoiser' from 'comfy.samplers' (C:\workspaces_c\comfyUI_20231115\ComfyUI\comfy\samplers.py)
```

**Comment by andreszs** [comment]
Same error here with **latest** comfyui version.
Incredibly, they persist in hiding the version number so I have no idea what version this would be.

**Comment by suito-venus** [comment]
CompVisVDenoiser is not used in efficiency-nodes-comfyui.
So work around below.
-------------------
\efficiency-nodes-comfyui\py\smZ_cfg_denoiser.py line 7
from comfy.samplers import KSampler, CompVisVDenoiser, KSamplerX0Inpaint
to 
from comfy.samplers import KSampler, KSamplerX0Inpaint
------------------
this worked for me.

**Comment by wangwenqiao666** [comment]
The following modifications can be made：

# from comfy.samplers import KSampler, CompVisVDenoiser, KSamplerX0Inpaint
# from comfy.k_diffusion.external import CompVisDenoiser
from comfy.samplers import KSampler, KSamplerX0Inpaint
from k_diffusion.external import CompVisDenoiser, CompVisVDenoiser

![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/55267900/0bfbf89b-3685-4ec6-a0cb-75370e4ef13c)

Then it will run without error
