### ISSUE TITLE
Pillow can't find `arial.tff` font if it's not in comfyUI root

### ISSUE THREAD

**Issue by LEv145** [LucianoCirino/efficiency-nodes-comfyui#3]
Error:
```py
Traceback (most recent call last):
  File "/opt/comfy_ui/execution.py", line 182, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "/opt/comfy_ui/execution.py", line 67, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "/opt/comfy_ui/custom_nodes/efficiency/efficiency_nodes.py", line 625, in sample
    font_size = adjusted_font_size(text, initial_font_size, img.width)
  File "/opt/comfy_ui/custom_nodes/efficiency/efficiency_nodes.py", line 549, in adjusted_font_size
    font = ImageFont.truetype('arial.ttf', initial_font_size)
  File "/usr/local/lib/python3.10/site-packages/PIL/ImageFont.py", line 996, in truetype
    return freetype(font)
  File "/usr/local/lib/python3.10/site-packages/PIL/ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/lib/python3.10/site-packages/PIL/ImageFont.py", line 248, in __init__
    self.font = core.getfont(
OSError: cannot open resource
```

The `README` file does not say that you need to download the font

How about adding the font to the root of the plugin?
`efficiency_nodes.py`:
```py
from pathlib import Path
FONT_PATH = Path(__file__).parent / "arial.ttf"
```

**Comment by LucianoCirino** [comment]
Can you please confirm this issue is fixed with the last update I just made to the repository?

**Comment by LucianoCirino** [comment]
Will close and assume issue was resolved.
