### ISSUE TITLE
XY plot manual script error

### ISSUE THREAD

**Issue by ltdrdata** [LucianoCirino/efficiency-nodes-comfyui#48]
[error-json.txt](https://github.com/LucianoCirino/efficiency-nodes-comfyui/files/12080351/error-json.txt)

```
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\Users\drltdata\git\ComfyUI\worklist_execution.py", line 42, in exception_helper
    task()
  File "C:\Users\drltdata\git\ComfyUI\worklist_execution.py", line 254, in task
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Users\drltdata\git\ComfyUI\execution.py", line 94, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Users\drltdata\git\ComfyUI\execution.py", line 87, in map_node_over_list
    results.append(getattr(obj, func)(**params))
  File "C:\Users\drltdata\git\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 1056, in sample
    image_pil_list = rearrange_list_A(image_pil_list, num_rows, num_cols)
UnboundLocalError: local variable 'image_pil_list' referenced before assignment
```
lora strength test script cause errors on latest version.

**Comment by LucianoCirino** [comment]
This should be fixed now, please update and try again.

**Comment by LucianoCirino** [comment]
Good to close?
