### ISSUE TITLE
[WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by tradiff** [LucianoCirino/efficiency-nodes-comfyui#54]
Looks like some great stuff here! Unfortunately, I'm having trouble installing it both manually and using the ComfyUI Manager. I have removed all other custom nodes, to rule out any possible conflict. I'm pretty new to this space, so I'm assuming it's probably something I'm doing wrong. Do you have any suggestions? Thanks!

<details>
  <summary>Logs here</summary>

```
C:\Users\Public\comfyui>.\python_embeded\python.exe -s ComfyUI\main.py --listen 
Total VRAM 8192 MB, total RAM 16314 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 SUPER : cudaMallocAsync
Using xformers cross attention
Adding extra search path checkpoints C:\Users\Public\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path configs C:\Users\Public\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae C:\Users\Public\stable-diffusion-webui\models/VAE
Adding extra search path loras C:\Users\Public\stable-diffusion-webui\models/Lora
Adding extra search path loras C:\Users\Public\stable-diffusion-webui\models/LyCORIS
Adding extra search path upscale_models C:\Users\Public\stable-diffusion-webui\models/ESRGAN
Adding extra search path upscale_models C:\Users\Public\stable-diffusion-webui\models/RealESRGAN
Adding extra search path upscale_models C:\Users\Public\stable-diffusion-webui\models/SwinIR
Adding extra search path embeddings C:\Users\Public\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks C:\Users\Public\stable-diffusion-webui\models/hypernetworks
Adding extra search path controlnet C:\Users\Public\stable-diffusion-webui\models/ControlNet
Traceback (most recent call last):
  File "C:\Users\Public\comfyui\ComfyUI\nodes.py", line 1516, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Public\comfyui\ComfyUI\custom_nodes\efficiency-nodes-comfyui\__init__.py", line 1, in <module>
    from .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "C:\Users\Public\comfyui\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 2334, in <module>
    install_simpleeval()
  File "C:\Users\Public\comfyui\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 2327, in install_simpleeval
    if 'simpleeval' not in packages():
  File "C:\Users\Public\comfyui\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 2332, in packages
    return [(r.decode().split('==')[0] if not versions else r.decode()) for r in subprocess.check_output([sys.executable, '-m', 'pip', 'freeze']).split()]
  File "subprocess.py", line 421, in check_output
  File "subprocess.py", line 503, in run
  File "subprocess.py", line 837, in __init__
  File "subprocess.py", line 1272, in _get_handles
OSError: [WinError 6] The handle is invalid

Cannot import C:\Users\Public\comfyui\ComfyUI\custom_nodes\efficiency-nodes-comfyui module for custom nodes: [WinError 6] The handle is invalid

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): C:\Users\Public\comfyui\ComfyUI\custom_nodes\efficiency-nodes-comfyui

Starting server

To see the GUI go to: http://0.0.0.0:8188
```  
</details>

**Comment by tradiff** [comment]
I got this fixed. It was related to me running comfyui as a windows service using nssm. I had to provide a stdin.txt file, and wire it up in nssm's config.
