### ISSUE TITLE
comfyui hangs when stopping

### ISSUE THREAD

**Issue by kj-kj-kj** [LucianoCirino/efficiency-nodes-comfyui#77]
Since the update this morning comfy hangs when quitting "python main.py". You have to press another ctrl-c to end:

Stopped server
^CException ignored in: <module 'threading' from '/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
KeyboardInterrupt:

This did not happen before the update.

**Comment by LucianoCirino** [comment]
I have attempted to fix this issue through the following commit:https://github.com/LucianoCirino/efficiency-nodes-comfyui/commit/2e42f33dcdde76a7f6939163366c257a713264e0

Please let me know if it fixes your issue.

**Comment by kj-kj-kj** [comment]
The error is indeed gone but it seems a new one was introduced:

When starting Comfyui with the extension active, it gives me following error when starting Comfyui:

### ComfyUI Revision: 1265 [1f0f4cc0]
Traceback (most recent call last):
  File "/Users/username/GitHub/ComfyUI/nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/username/GitHub/ComfyUI/custom_nodes/efficiency-nodes-comfyui/__init__.py", line 1, in <module>
    from .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "/Users/username/GitHub/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 43, in <module>
    from tsc_utils import *
  File "/Users/username/GitHub/ComfyUI/custom_nodes/efficiency-nodes-comfyui/tsc_utils.py", line 491, in <module>
    install_packages(my_dir)
  File "/Users/username/GitHub/ComfyUI/custom_nodes/efficiency-nodes-comfyui/tsc_utils.py", line 477, in install_packages
    installed_packages = packages(embedded_python_exe, versions=False)
  File "/Users/username/GitHub/ComfyUI/custom_nodes/efficiency-nodes-comfyui/tsc_utils.py", line 488, in packages
    subprocess.check_output([python_exe, '-m', 'pip', 'freeze']).split()]
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/username/GitHub/python_embeded/python.exe'

Cannot import /Users/username/GitHub/ComfyUI/custom_nodes/efficiency-nodes-comfyui module for custom nodes: [Errno 2] No such file or directory: '/Users/username/GitHub/python_embeded/python.exe'

Please note that I am using a venv setup on macos; my python binary for comfyui is /Users/koen/GitHub/ComfyUI/venv/bin/python

Thank you!

**Comment by LucianoCirino** [comment]
Okay no problem, let me come up with another solution.

**Comment by LucianoCirino** [comment]
@kj-kj-kj , can you please try seing if this branch of Efficiency Nodes fixes your Venv environment issues?

https://github.com/LucianoCirino/efficiency-nodes-comfyui/tree/Implement-fallback-for-pip-installations

**Comment by alexopus** [comment]
I had all the same issues and with your test branch it no longer hangs nor fails on startup.

**Comment by kj-kj-kj** [comment]
with this branch all works OK, thanks!

**Comment by LucianoCirino** [comment]
Great! PR has been merged with main branch. https://github.com/LucianoCirino/efficiency-nodes-comfyui/pull/85
