### ISSUE TITLE
Startup Failure with latest update

### ISSUE THREAD

**Issue by Piscabo** [LucianoCirino/efficiency-nodes-comfyui#86]
**Newest update cause this startup issue?**
Traceback (most recent call last):
  File "C:\AI_Files\ComfyUI\nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI_Files\ComfyUI\custom_nodes\efficiency-nodes-comfyui\__init__.py", line 1, in <module>
    from .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "C:\AI_Files\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 43, in <module>
    from tsc_utils import *
  File "C:\AI_Files\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_utils.py", line 493, in <module>
    install_packages(my_dir)
  File "C:\AI_Files\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_utils.py", line 479, in install_packages
    installed_packages = packages(embedded_python_exe, versions=False)
  File "C:\AI_Files\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_utils.py", line 490, in packages
    subprocess.check_output([python_exe, '-m', 'pip', 'freeze']).split()]
  File "C:\Programs\Python\Python310\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Programs\Python\Python310\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

Cannot import C:\AI_Files\ComfyUI\custom_nodes\efficiency-nodes-comfyui module for custom nodes: [WinError 2] The system cannot find the file specified

**Comment by Piscabo** [comment]
_OK, I fixed the script and now works for me:_ 
Open the **tsc_utils.py** file.
Locate the **install_packages function.**
Replace the entire function with the following code:

import sys
import subprocess

def install_packages(my_dir):
    embedded_python_exe = sys.executable
    
    # List of required packages
    required_packages = [
        "numpy",
        "Pillow",
        "torch",
        "torchvision",
        "websockets",
        # Add any other required packages here
    ]
    
    for package in required_packages:
        try:
            __import__(package)
        except ImportError:
            subprocess.check_call([embedded_python_exe, '-m', 'pip', 'install', package])

**Comment by LucianoCirino** [comment]
Did you attempt to run with the latest commit instead of your temporary hack? 🤠

**Comment by Piscabo** [comment]
> Yes, all fine now thank you. I always try and look for a solution myself first, and posting to help, than just saying it is 'broke'. Thanks for your amazing shared work...
