### ISSUE TITLE
Error on startup fresh install 

### ISSUE THREAD

**Issue by mariogomezr** [LucianoCirino/efficiency-nodes-comfyui#87]
Got this error on a fresh install, latest version of ComfyUI and folder from the direct download link. 

Traceback (most recent call last):
  File "/home/mario/Desktop/AI/ComfyUI/nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mario/Desktop/AI/ComfyUI/custom_nodes/efficiency-nodes-comfyui/__init__.py", line 1, in <module>
    from .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "/home/mario/Desktop/AI/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 43, in <module>
    from tsc_utils import *
  File "/home/mario/Desktop/AI/ComfyUI/custom_nodes/efficiency-nodes-comfyui/tsc_utils.py", line 41, in <module>
    last_helds: dict[str, list] = {
TypeError: 'type' object is not subscriptable

**Comment by LucianoCirino** [comment]
@mariogomezr 

I had fixed this issue this morning on the Github repo but did not update the release files. Just updated them. Please try again! [Direct Download](https://github.com/LucianoCirino/efficiency-nodes-comfyui/releases/download/v1.72/efficiency-nodes-comfyui_V1-72.zip)

**Comment by LucianoCirino** [comment]
Any luck friend?

**Comment by mariogomezr** [comment]
Hey friend, had the same issue :/. 
![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/47620428/87516cf0-7a32-4d25-b214-f999b4d1bc28)

**Comment by LucianoCirino** [comment]
Okay so from some research it seems this error might be tied to the fact you are running an older version of python (older than 3.9). I made a pull request that might fix this particular issue as a test, but I have no clue if you will run into another issue with some other library next.

https://github.com/LucianoCirino/efficiency-nodes-comfyui/tree/Fix-TypeError-in-tsc_utils.py-related-to-type-hinting

If you want to attempt this patch manually, open "tscutils.py" in notepad and add the changes seen below: https://github.com/LucianoCirino/efficiency-nodes-comfyui/pull/88/files

"from typing import Dict, List"

... If you run into more issues after this attemppted fix and you **do** happen to an older version of python installed (<3.9), consider upgrading python :^)
