### ISSUE TITLE
'type' object is not subscriptable

### ISSUE THREAD

**Issue by Nechochwen-D** [LucianoCirino/efficiency-nodes-comfyui#9]
Been getting this error whenever I try to use these nodes recently
```
Traceback (most recent call last):
  File "/home/USER/ComfyUI/nodes.py", line 1273, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/david/ComfyUI/custom_nodes/efficiency_nodes.py", line 302, in <module>
    last_helds: dict[str, list] = {
TypeError: 'type' object is not subscriptable

Cannot import /home/USER/ComfyUI/custom_nodes/efficiency_nodes.py module for custom nodes: 'type' object is not subscriptable
```

**Comment by LucianoCirino** [comment]
Can you give a bit more info? try the latest build on Github.
