### ISSUE TITLE
(IMPORT FAILED) error when first importing

### ISSUE THREAD

**Issue by ergosk** [LucianoCirino/efficiency-nodes-comfyui#95]
Hi, I am new to comfyui and was trying to use your nodes since it's seems very orderly and simple.
However I was having an issue when I tried to import the nodes.
I was wondering if you can help with this. Your help is much appreciated.
Below is the cmd log, 

Efficiency Nodes: Installing required package 'simpleeval'...Traceback (most recent call last):
  File "D:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\__init__.py", line 1, in <module>
    from .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "D:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 43, in <module>
    from tsc_utils import *
  File "D:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_utils.py", line 500, in <module>
    install_packages(my_dir)
  File "D:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_utils.py", line 485, in install_packages
    subprocess.check_call(['pip', 'install', pkg, '--target=' + target_dir, '--no-warn-script-location',
  File "subprocess.py", line 369, in check_call
subprocess.CalledProcessError: Command '['pip', 'install', 'simpleeval', '--target=D:\\AI\\ComfyUI\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages', '--no-warn-script-location', '--disable-pip-version-check']' returned non-zero exit status 1.

Cannot import D:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui module for custom nodes: Command '['pip', 'install', 'simpleeval', '--target=D:\\AI\\ComfyUI\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages', '--no-warn-script-location', '--disable-pip-version-check']' returned non-zero exit status 1.

Import times for custom nodes:
   1.8 seconds (IMPORT FAILED): D:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui

**Comment by LucianoCirino** [comment]
Hello @ergosk , it looks like the auto installation of the required package "simpleeval" failed. Could you try manually installing them with the following commands?

```
pip install simpleeval websockets
```

**Comment by ergosk** [comment]
Hi @LucianoCirino . I did what you said but it didn't work at first, somehow simpleeval and websockets still seems to be undetected. Tried to install with --target and it finally worked. Thank you for your help.

**Comment by ergosk** [comment]
Hi @LucianoCirino . I did what you said but it didn't work at first, somehow simpleeval and websockets still seems to be undetected. Tried to install with --target and it finally worked. Thank you for your help.
